### ISSUE TITLE
Synthesizer instance has no attribute '_reconstruct'

### ISSUE THREAD

**Issue by robotnc** [namalkanti/vocoder#1]
Hi, I run your code and meet some problem about Class Synthesizer():
 34     def _reconstruct_frames(self):
 35         frames = self.get_frame_array().get_frames()
 36         return np.asarray(map(self._reconstruct, frames))

AttributeError: Synthesizer instance has no attribute '_reconstruct'

**Comment by namalkanti** [comment]
Sorry about the late response; I moved the method from the class body into a function, but I forgot to update that line. I've pushed that change along with a full update to Python3
